# roles/hosts/tasks/main.yml
---

## - name: Install custom hosts file
##   template:
##     src: etc_hosts.j2
##     dest: "{{ hosts_file }}"
##     owner: root
##     group: root
##     mode: 0644
##     backup: "{{ host_file_backup }}"
##   tags: hosts

## - name: render host_entries
##   debug: msg="{{ hosts_entries }}"

- name: render custom hosts template
  set_fact: 
    custom_hosts: "{{ lookup('template', 'custom_hosts.j2') }}"

## - name: render debug
##   debug: msg="{{ lookup('template', 'custom_hosts.j2') }}"

- name: Add Managed Block to {{ hosts_file }}
  blockinfile:
    path: "{{ hosts_file }}"
    owner: root
    group: root
    content: "{{ custom_hosts }}"
    marker: "# {{ hosts_custom_hosts_marker }} {mark}"
